#        _          _          _ _
#  _ __ (_)_  _____| | ___  __| (_)
# | '_ \| \ \/ / _ \ |/ _ \/ _` | |
# | |_) | |>  <  __/ |  __/ (_| | |
# | .__/|_/_/\_\___|_|\___|\__,_|_|
# |_|
# https://links.pixeledi.eu
# CYD mit ESPHome | 05.2025
#
substitutions:
  device_name: cyd 
  friendly_name: cyd 

esphome:
  name: $device_name
  friendly_name: $friendly_name

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: backlight
    restore_mode: ALWAYS_ON

# Details von GPIOs findet man auch unter :/home/deinuser/Arduino/libraries/TFT_eSPI/User_Setup.h 
spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm

sensor:
  - platform: template
    name: "Template Sensor"
    id: sensor1
    on_value:
      - lvgl.indicator.update:
              id: temperature_needle
              value: !lambda return x * 10;
      - lvgl.label.update:
          id: temperature_text
          text:
            format: "%.1f°C"
            args: [ 'x' ]     


interval:
  - interval: 1s
    then:
      lambda: |-
         static int value1 = 0;
         id(sensor1).publish_state(value1++);
          
lvgl:
  buffer_size: 25%
  touchscreens:
    - my_touch
  pages:
    - id: meter_page
      widgets:
        - meter:
            align: CENTER
            height: 180
            width: 180
            scales:
              - range_from: -100 # scale for the needle value
                range_to: 400
                angle_range: 240
                rotation: 150
                indicators:
                  - line:
                      id: temperature_needle
                      width: 2
                      color: 0xFF0000
                      r_mod: -4
                  - tick_style:
                      start_value: -10
                      end_value: 40
                      color_start: 0x0000bd
                      color_end: 0xbd0000
                      width: 1
              - range_from: -10 # scale for the value labels
                range_to: 40
                angle_range: 240
                rotation: 150
                ticks:
                  width: 1
                  count: 51
                  length: 10
                  color: 0x000000
                  major:
                    stride: 5
                    width: 2
                    length: 10
                    color: 0x404040
                    label_gap: 10
            widgets:
              - label:
                  id: temperature_text
                  text: "-.-°C"
                  align: CENTER
                  y: 45
              - label:
                  text: "Outdoor"
                  align: CENTER
                  y: 65


touchscreen:
  - platform: xpt2046
    id: my_touch
    spi_id: touch
    cs_pin: GPIO33
    interrupt_pin: GPIO36
    calibration:
      x_min: 200
      x_max: 3900
      y_min: 200
      y_max: 3900   
    transform:
      mirror_x: false
      mirror_y: false
      swap_xy: false


# CYD = ili9xxx platform
display:
  - platform: ili9xxx
    model: ili9341
    spi_id: tft 
    cs_pin: GPIO15
    dc_pin: GPIO2
    rotation: 90
    invert_colors: false
    # color_palette: 8BIT
    auto_clear_enabled: false
    update_interval: never
